on: [commit]
jobs:
  runs-on: ubuntu-latest
    steps:
      # This step references the directory that contains the action.
      - name: Use local hello-world-action
        uses: ./.github/actions/semver

      

